In [10]:
import cv2

In [11]:
img =cv2.imread('lena.jpg', 1)
print(img)

[[[128 138 225]
  [127 137 224]
  [126 136 224]
  ...
  [126 145 236]
  [110 129 220]
  [ 86 104 197]]

 [[127 137 224]
  [127 137 224]
  [127 137 224]
  ...
  [130 150 235]
  [112 132 217]
  [ 83 102 189]]

 [[127 137 224]
  [127 137 224]
  [128 138 225]
  ...
  [127 148 230]
  [112 133 215]
  [ 85 105 190]]

 ...

 [[ 55  21  82]
  [ 54  20  81]
  [ 62  28  92]
  ...
  [ 82  71 175]
  [ 78  68 175]
  [ 74  65 175]]

 [[ 55  18  80]
  [ 56  19  81]
  [ 66  32  96]
  ...
  [ 82  69 177]
  [ 80  71 181]
  [ 81  72 183]]

 [[ 56  19  81]
  [ 58  21  83]
  [ 68  34  98]
  ...
  [ 81  68 176]
  [ 81  72 183]
  [ 84  74 188]]]


In [13]:
# img.type() is numpy array

In [17]:
cv2.imshow('image', img)
k = cv2.waitKey(0)
# shows image for 5sec 
if k == 27: # 27 => esc key
    cv2.destroyAllWindows()
elif k == ord('s'):
    cv2.imwrite("lena_copy.png",img)
    cv2.destroyAllWindows()

In [15]:
cv2.imwrite("lena_copy.png",img) 
# creating img called lena_copy.png

True

In [35]:
cap = cv2.VideoCapture(0)
# getting available camera
# 0 or -1 device index
# multiple cameras 1,2..

fourcc = cv2.VideoWriter_fourcc(*'XVID')
# fourcc = cv2.VideoWriter_fourcc('X','V','I','D')

out = cv2.VideoWriter('output.avi', fourcc, 20.0, (640,480))
# saving the video
#(name of file, source, frame speed, size of the video)

print(cap.isOpened())
# whether the camera is available or not

while(cap.isOpened()):
    ret, frame = cap.read()
    
    if ret == True:
        print(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        print(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        
        out.write(frame)
#       저장시키는 명령어

        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        cv2.imshow('frame',gray)

        if cv2.waitKey(1) == ord('q'):
            break
    else:
        break


cap.release()
out.release()
cv2.destroyAllWindows()


True
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
