In [2]:
'''How to read, Write, Show Videos from Camera'''

import cv2

In [2]:
img =cv2.imread('lena.jpg', 1)
# print(img)

In [3]:
# img.type() is numpy array

In [8]:
cv2.imshow('image', img)
k = cv2.waitKey()
cv2.destroyAllWindows()
# shows image for 5sec 

# if k == 27: # 27 => esc key
#     cv2.destroyAllWindows()
# elif k == ord('s'):
#     cv2.imwrite("lena_copy.png",img)
#     cv2.destroyAllWindows()

In [5]:
cv2.imwrite("lena_copy.png",img) 
# creating img called lena_copy.png

True

In [5]:
'''how to read write show videos from camera'''
import cv2
cap = cv2.VideoCapture(0)
# getting available camera
# 0 or -1 device index
# multiple cameras 1,2..

fourcc = cv2.VideoWriter_fourcc(*'XVID')
# fourcc = cv2.VideoWriter_fourcc('X','V','I','D')

out = cv2.VideoWriter('output.avi', fourcc, 20.0, (640,480))
# saving the video
#(name of file, source, frame speed, size of the video)

print(cap.isOpened())
# whether the camera is available or not

while(cap.isOpened()):
    ret, frame = cap.read()

    if ret == True:
    #         print(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    #         print(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

        out.write(frame)
    #       저장시키는 명령어 from VideoWriter

        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        cv2.imshow('frame',gray)

        if cv2.waitKey(1) == ord('q'):
            break
    else:
        break
#이 else가 없어야지 말이됨 아니면 바로 꺼짐

#without while loop smt pops up and disappears

# cap.release()
# out.release()
####releassing software/hardware resource allocated to that variable###
cv2.destroyAllWindows()
##이거 없으면 에러뜸


True


In [4]:
cap = cv2.VideoCapture(0)

print(cap.isOpened())

while(cap.isOpened()):
    ret,frame = cap.read()
    print(ret)
    if ret == True:
        cv2.imshow('camera',frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    else:
        break
cv2.destroyAllWindows()

True
False


In [21]:
'''Draw Geometric shapes on images'''
import cv2
import numpy as np

img = cv2.imread('lena.jpg',1)
#or
img = np.zeros([512,512,3], dtype=np.uint8)
#검정색 바탕의 이미지를 불러옴

img = cv2.line(img, (0,0), (255,255), (0,0,255), 10)
# draw line image, start coordinate(x=width,y=height), end coordinate, BGR, line thickness

img = cv2.arrowedLine(img, (0,255), (255,255), (0,0,255), 10)
#draw arrowed line

img = cv2.rectangle(img, (0,0), (255,255), (255,0,0), -1)
#맨끝에 -1이오면 그색깔로 사각형을 fill함 or cv2.FILLED

img = cv2.circle(img, (447,63), 100, (0,255,0), -1)

font = cv2.FONT_HERSHEY_SIMPLEX
img = cv2.putText(img, "OpenCV", (10,500), font, 4, (255,255,255), 10, cv2.LINE_AA)
#image, 텍스트, 텍스트 시작 coordinate, 폰트 타입, 폰트사이즈, 색깔, 글씨 thickness, Line type


cv2.imshow('image', img)
k = cv2.waitKey(0)

if k == ord('q'):
    cv2.destroyAllWindows()

In [15]:
import numpy as np
img = np.zeros([512,512,3], dtype=np.uint8)
#512x3인 zeros가 512개의 filter/batch로 존재
print(img.shape)

(512, 512, 3)


In [1]:
'''Setting Camera Parameters'''
import cv2
cap = cv2.VideoCapture(0)
print(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
print(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

cap.set(3, 1208)
#changing proeprty index(3 means frame width), 1208 means cpature width
cap.set(4, 720)
#changing proeprty index(4 means frame height), 720 means cpature height


print(cap.get(3))
###every camera property has defined number###
print(cap.get(4))

while(cap.isOpened()):
    ret, frame = cap.read()
    if ret == True:
        
#         gray = cv2.cvtColor(frame,)
        cv2.imshow('frame', frame)
        
    if cv2.waitKey(1) == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

640.0
480.0
1280.0
720.0


In [2]:
'''Show Date and Time on Video'''
import cv2
import datetime

cap = cv2.VideoCapture(0)
# print(cap.get(3))
# print(cap.get(4))
# cap.set(3,1280)
# cap.set(4,720)

while(cap.isOpened()):
    ret, frame = cap.read()
    if ret == True:
        
        font = cv2.FONT_HERSHEY_SIMPLEX
        text = 'Width: ' + str(cap.get(3)) + 'Height: ' + str(cap.get(4))
        date = str(datetime.datetime.now())
        frame = cv2.putText(frame, date, (10,50), font, 1, 
                            (0,255,255), 2, cv2.LINE_AA)
#         image, text, starting coordinate, font, font scale, text color,
#         text thickness, text style
        cv2.imshow('frame', frame)
        
        if cv2.waitKey(1) == ord('q'):
            break
#             cv2.waitKey(0)했더니만 무수히많은 스크린샷들이 나옴
#     else:
#         break
        
cap.release()
cv2.destroyAllWindows()
######이거없으면 비디오 창 닫을때 에러오짐
        

In [21]:
'''Handle Mouse Events'''
import numpy as np
import cv2

events = [i for i in dir(cv2) if 'EVENT' in i]
# dir shows all the classes, functions, variables in package
print(events)

###x,y is coordinates
def click_event(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        print(x, ',',y)
        font = cv2.FONT_HERSHEY_SIMPLEX
        strXY = str(x) + ',' + str(y)
        cv2.putText(img, strXY, (x,y), font, 1, (255,255,0), 2)
        cv2.imshow('image', img)
    elif event == cv2.EVENT_RBUTTONDOWN:
        blue = img[y, x, 0]
        green = img[y, x, 1]
        red = img[y, x, 2]
        font = cv2.FONT_HERSHEY_SIMPLEX
        strBGR = str(blue) + ',' + str(green) + ',' + str(red)
        cv2.putText(img, strBGR, (x,y), font, 1, (0,255,255), 2)
        cv2.imshow('image', img)
    
# img  = np.zeros((512,512,3), np.uint8)
### black image

img = cv2.imread('lena.jpg',1)
cv2.imshow('image',img)

cv2.setMouseCallback('image', click_event)
#### 'image'이거 이름은 callback function안에 지정해둔 이름과 cv2.imshow('image',img)
#### 이름과 동일해야함
#'image', callbackfucntion(i.e. click_event)

cv2.waitKey()
cv2.destroyAllWindows()
    
    

['EVENT_FLAG_ALTKEY', 'EVENT_FLAG_CTRLKEY', 'EVENT_FLAG_LBUTTON', 'EVENT_FLAG_MBUTTON', 'EVENT_FLAG_RBUTTON', 'EVENT_FLAG_SHIFTKEY', 'EVENT_LBUTTONDBLCLK', 'EVENT_LBUTTONDOWN', 'EVENT_LBUTTONUP', 'EVENT_MBUTTONDBLCLK', 'EVENT_MBUTTONDOWN', 'EVENT_MBUTTONUP', 'EVENT_MOUSEHWHEEL', 'EVENT_MOUSEMOVE', 'EVENT_MOUSEWHEEL', 'EVENT_RBUTTONDBLCLK', 'EVENT_RBUTTONDOWN', 'EVENT_RBUTTONUP']
177 , 126
190 , 208
84 , 207
191 , 247


In [18]:
'''More Mouse Event Examples'''
import numpy as np
import cv2

events = [i for i in dir(cv2) if 'EVENT' in i]
# dir shows all the classes, functions, variables in package
print(events)

###x,y is coordinates
def click_event(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        cv2.circle(img, (x,y), 3, (0,0,255), -1)
        points.append((x,y))
        if len(points) >= 2:
            cv2.line(img, points[-1], points[-2], (255,0,0), 5)
        cv2.imshow('image', img)
    
    
img  = np.zeros((512,512,3), np.uint8)
### black image

# img = cv2.imread('lena.jpg',1)
cv2.imshow('image',img)
points=[]

cv2.setMouseCallback('image', click_event)
#### 'image'이거 이름은 callback function안에 지정해둔 이름과 cv2.imshow('image',img)
#### 이름과 동일해야함
#'image', callbackfucntion(i.e. click_event)

cv2.waitKey()
cv2.destroyAllWindows()

['EVENT_FLAG_ALTKEY', 'EVENT_FLAG_CTRLKEY', 'EVENT_FLAG_LBUTTON', 'EVENT_FLAG_MBUTTON', 'EVENT_FLAG_RBUTTON', 'EVENT_FLAG_SHIFTKEY', 'EVENT_LBUTTONDBLCLK', 'EVENT_LBUTTONDOWN', 'EVENT_LBUTTONUP', 'EVENT_MBUTTONDBLCLK', 'EVENT_MBUTTONDOWN', 'EVENT_MBUTTONUP', 'EVENT_MOUSEHWHEEL', 'EVENT_MOUSEMOVE', 'EVENT_MOUSEWHEEL', 'EVENT_RBUTTONDBLCLK', 'EVENT_RBUTTONDOWN', 'EVENT_RBUTTONUP']


In [1]:
import numpy as np
import cv2

def click_event(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        blue = img[x,y,0]
        ##same way of indexing an array like img[x][y][0]
        #remember, img array is 512,512,3 where channel, height, width
        green = img[x,y,1]
        red = img[x,y,2]
        cv2.circle(img, (x,y), 3, (0,0,255), -1)
        mycolorimage = np.zeros((512,512,3), np.uint8)
        
        mycolorimage[:] = [blue, green ,red]
        
        cv2.imshow('color', mycolorimage)

img = cv2.imread('lena.jpg',1)
cv2.imshow('image',img)

cv2.setMouseCallback('image', click_event)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [37]:
import cv2
import numpy as np
img = cv2.imread('lena.jpg',1)
print(len(img[0]))
blue=  img[0][0][0]
print(blue)

##opencv에서 cv2.imread한 image는 아마도 (512,512,3)이면 3이 BGR을 뜻하고
##첫번째 512가 x coordinate 두번째 512가 y coordinate을 나타낸다
##so like in channel wise it shows x coordinates
## and in one channel each row represents y coordinate

512
128


In [6]:
import numpy.random as rd
a = rd.randn(4,3,3)
print(a)
print('------')
print(a[0])
print(a[0][0])
print('\n')
print(a[:,0])
a[:]=255,0,0
# print(b)
print(a[:])
#getting first row of all the channels

[[[ 2.17691853  0.60107686 -0.1499704 ]
  [ 0.63746245 -1.81666025  0.06456691]
  [ 1.78771895 -0.39859026  0.84064198]]

 [[ 1.35434824  1.3777332  -0.60726082]
  [ 0.02407242  0.22602255 -0.79709878]
  [ 1.43121376  0.39488294  1.2367611 ]]

 [[ 1.06753228  0.23419964  0.12902977]
  [-0.3924453  -0.18379117 -0.49183802]
  [ 0.38439591 -2.7024487   0.47467421]]

 [[ 0.42519436  2.12117484 -1.31253326]
  [ 1.21155108 -0.16063377  0.59330619]
  [-0.67566536 -1.29863262  0.50535613]]]
------
[[ 2.17691853  0.60107686 -0.1499704 ]
 [ 0.63746245 -1.81666025  0.06456691]
 [ 1.78771895 -0.39859026  0.84064198]]
[ 2.17691853  0.60107686 -0.1499704 ]


[[ 2.17691853  0.60107686 -0.1499704 ]
 [ 1.35434824  1.3777332  -0.60726082]
 [ 1.06753228  0.23419964  0.12902977]
 [ 0.42519436  2.12117484 -1.31253326]]
[[[255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]]

 [[255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]]

 [[255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]]

 [[255.   0. 